"""empty message

Revision ID: 95170eff0e71
Revises: 33d0dde8aa7f
Create Date: 2023-07-29 02:24:17.249413

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '95170eff0e71'
down_revision = '33d0dde8aa7f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('comments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('posted', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('comments', schema=None) as batch_op:
        batch_op.drop_column('posted')

    # ### end Alembic commands ###
