"""empty message

Revision ID: d2fa75da23c9
Revises: 1858048b45ae
Create Date: 2023-07-29 13:14:09.794070

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd2fa75da23c9'
down_revision = '1858048b45ae'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('comments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('commenter_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'users', ['commenter_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('comments', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('commenter_id')

    # ### end Alembic commands ###
